// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSxRuVTA-nZ7T_2X8FfFAbPIix1zU3ZU',
    appId: '1:55510306996:web:b2471bc5981c9318de87e1',
    messagingSenderId: '55510306996',
    projectId: 'otlob-gas',
    authDomain: 'otlob-gas.firebaseapp.com',
    storageBucket: 'otlob-gas.appspot.com',
    measurementId: 'G-Y3E5FTDLL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQs5uLGoHlA2bu0VpVRm8b1LCuxU4L3w',
    appId: '1:55510306996:android:e838f9c3322f0f9cde87e1',
    messagingSenderId: '55510306996',
    projectId: 'otlob-gas',
    storageBucket: 'otlob-gas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-Q7V-I50wGNVvp1imh7eUgPs8ca6St8',
    appId: '1:55510306996:ios:cd48743038dcc7f2de87e1',
    messagingSenderId: '55510306996',
    projectId: 'otlob-gas',
    storageBucket: 'otlob-gas.appspot.com',
    iosClientId: '55510306996-eq19l8siplaedho9mffgsgh6vss4k0tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.otlobGas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-Q7V-I50wGNVvp1imh7eUgPs8ca6St8',
    appId: '1:55510306996:ios:cd48743038dcc7f2de87e1',
    messagingSenderId: '55510306996',
    projectId: 'otlob-gas',
    storageBucket: 'otlob-gas.appspot.com',
    iosClientId: '55510306996-eq19l8siplaedho9mffgsgh6vss4k0tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.otlobGas',
  );
}
